= Работа с электронной почтой в GNU/Linux
Коротков А. В.
2002
// Metadata:
:description: Работа с электронной почтой в GNU/Linux.
:keywords: email, Linux
// Settings:
:experimental:
:icons: font
:lang: ru
:source-highlighter: pygments
:source-language: console
:pygments-style: emacs
:pygments-linenums-mode: inline
:note-caption: Примечание
:important-caption: Важно

Когда мне в ящике письменного стола попадается на глаза пожелтевший от
времени конверт — вспоминается, что письма когда-то были бумажными,
письмо из Москвы в мой родной Ижевск могло идти неделю, а могло
и потеряться или прийти грязным и рваным. Я уже десять лет не пишу писем
по старинке, на бумаге, а за три года пользования электронной почтой
в моём компьютерном ящике скопилось почти сто тысяч писем. Конечно,
всякая медаль имеет две стороны: на бумаге пишешь всё же обстоятельно,
тщательно обдумывая каждую фразу — вымарывать или переписывать не очень
хочется, да и писать доводилось редко; электронная почта прививает
совсем иной стиль… Но не будем о грустном — оперативность, возможность
познакомиться с интересными тебе людьми, которых бы ты никогда в жизни
лично не повстречал и многое другое — несомненные плюсы почты именно
электронной.

В статье Виктора Вагнера про терминалы вы можете прочитать о пользе почтовых
ящиков для «внутриквартирного» использования. Конечно, это — лишь одно из
возможных применений электронной почты, основное её назначение всё же — общение
с людьми, живущими не в соседней комнате. В наше время свой почтовый ящик имеет
почти любая городская организация, многие владельцы домашних компьютеров и даже
люди, не имеющие собственной техники — этому способствуют распространившиеся
Интернет-кафе и подобные им заведения. Как выглядит адрес электронной почты,
сейчас знает каждый хотя бы благодаря рекламе, но что происходит, когда, набрав
vasya@pupkin.ru в поле «кому» и «набив» текст письма, вы нажимаете кнопку
«отправить» вашего почтовика?

Функционирование любых коммуникационных программ основано на сетевых интерфейсах
(т. е. способах взаимодействия); регулируют взаимодействие компьютеров,
соединённых каналами связи, т. н. протоколы — наборы правил, стандартов. Эти
стандарты описаны в ряде документов, принятых различными международными
организациями; они постоянно развиваются. Рабочая группа инженеров Internet
(IETF — Internet Engineering Task Force) разрабатывает документы серии RFC
(Request for Comments — запрос для комментариев).

Та программа, с которой вы будете непосредственно иметь дело, работая с почтой,
относится к классу MUA (Mail User Agent, пользовательский почтовый агент). В ней
вы читаете приходящую почту, пишете письма сами и отвечаете на поступившие к
вам. Таких программ существует очень много, выбор почтового клиента — дело вкуса
и ваших потребностей.

Сообщение электронной почты, в соответствии с RFC-822, состоит из двух частей —
заголовков и тела сообщения. Заголовки отделяются от тела сообщения пустой
строкой и содержат, в частности, такую необходимую информацию, как адреса
отправителя и получателя, дату, тему сообщения.

После того как вы дали команду вашему MUA отправить письмо, оно тут же
передаётся программе другого класса, MTA (Mail Transport Agent, агент отправки
почты), среди которых стандартом является http://www.sendmail.org[Sendmail],
чаще заменяемый в нынешних дистрибутивах Linux одной из более современных
программ, таких как http://www.postfix.org[Postfix], http://www.exim.org[Exim]
или http://www.qmail.org[Qmail]. Задача MTA, как следует из его названия —
передать ваше письмо адресату. Процесс отправки почты по сети Internet
регулируется протоколом SMTP (Simple Mail Transfer Protocol, простой протокол
отправки почты), при этом ваша программа инициирует соединение с сервером,
который доставляет ваше сообщение адресату. Процесс получения почты основан на
протоколе POP3 (Post Office Protocol, почтовый протокол); при этом ваша
клиентская программа устанавливает TCP/IP соединение с сервером, передаёт ваши
почтовые логин и пароль и после успешной идентификации может принимать и удалять
почту с вашего ящика на сервере; вообще говоря, этот протокол предусматривает
возможность и отправки сообщений. Есть также и другие протоколы получения и
доставки почты, например, IMAP (Internet Message Access Protocol, почтовый
протокол Internet доступа к сообщениям) — когда ваша почта хранится не на вашем
компьютере, а на почтовом сервере. Работающие у вашего провайдера сервер SMTP, а
у провайдера вашего адресата — сервер POP3 позволяют соответственно — вам
отправить письмо, а вашему адресату — его получить. Вся почта, доставляемая на
ваш адрес, хранится в вашем ящике у провайдера — до тех пор, пока вы её не
затребуете. Наверно, все современные MUA умеют работать с удалённым почтовым
сервером по протоколу POP3, но лучше воспользоваться одной из программ,
специально для этого предназначенных — стандартом de facto среди них является в
открытых системах http://www.tuxedo.org/~esr/fetchmail[Fetchmail]. После
получения, сообщение передаётся программе класса MDA (Mail Delivery Agent, агент
доставки почты), в качестве которой в Linux обычно выступает
http://www.procmail.org[Procmail]. Задачей MDA является добавление очередных
сообщений в почтовый ящик, располагаемый, как правило, в _/var/mail/user_,
откуда ваш MUA может почту забрать, после чего он помещает её обычно в свой
специальный каталог, расположенный внутри вашего домашнего. Наиболее часто
сейчас используемые форматы хранения почты — mbox, когда почта хранится в одном
файле, (при этом MUA может отделять одно письмо от другого по строкам «From»,
т. е. «от кого») и MH — когда каждое сообщение хранится в отдельном файле, а
также maildir.

Первоначально стандартами не предусматривалась передача в теле письма ничего
другого, кроме текста, причём только с символами, входящими в стандартный набор
us-ascii (7-битные сообщения). Сейчас вы можете писать свои письма на любом
языке, например, русском. К сожалению, различных наборов символов (кодировок),
используемых для русского языка, более чем много — koi8-r (стандарт для *nix),
cp1251 (или windows-1251, применяется в ОС от Microsoft семейства Windows),
cp866 (т. н. «альтернативная» кодировка; используется в MS-DOS, её клонах и
OS/2), ISO-8859-5 (предложена ISO — International Organization for
Standartization, Международной организацией по стандартизации; не получила в
России распространения), x-mac-cyrillic (применяется в MAC OS). Многие
современные почтовые клиенты поддерживают все эти варианты и даже умеют сами
распознавать, какой набор символов использован в сообщении, но всё же часто это
создаёт проблемы, особенно тем, кто получает почту, посланную программами,
нарушающими стандарты. По причинам, имеющим уже только историческое значение,
стандартом de facto в Рунете является кодировка koi8-r, поэтому рекомендуется
настраивать почтовый клиент так, чтобы он отправлял сообщения именно в этой
кодировке [#back_1]## ##link:#foot_1[[1]].

Обеспечивает возможность пересылки 8-битных текстов спецификация MIME
(Multipurpose Internet Mail Extensions, многоцелевые расширения почтового
стандарта Internet). Помимо использования наборов символов, отличных от
us-ascii, этот стандарт позволяет:

* передавать любые данные — программы, архивы, графические файлы — всё, что вы
пожелаете;
* посылать комбинированные сообщения, содержащие разнородные части, причём так,
чтобы клиентская программа могла определить, что делать с каждой из частей.

Используемый вами почтовый клиент может иметь встроенную систему
кодирования/декодирования таких сообщений. Чтобы обеспечить пересылку бинарных
файлов в нетронутом виде, их нужно закодировать в текстовый 7-битный формат.
Имеются разные алгоритмы такого кодирования, до появления MIME использовались
Uuencode/Uudecode, в MIME для этого предназначается Base64. Метод кодирования
указывается в заголовках письма, для этого предназначено поле
Content-Transfer-Encoding. Если вы, открыв письмо в текстовом редакторе (чтобы
видеть его «как есть»), обнаружите в теле сообщения ровные строчки латинских
символов, посмотрите его заголовки — там вы, скорее всего, увидите строчку:

[source,edit]
----
Content-Transfer-Encoding: base64
----

Другой алгоритм MIME-кодирования, Quited-Printable, предназначен для
преобразования данных, состоящих, в основном, из байтов, соответствующих
символам в us-ascii, эти символы остаются нетронутыми. Если, проделав
предложенный выше эксперимент, вы увидите строчки, подобные таким:

[source,edit]
----
=ED=CF=D6=C5=D4 =D5 =CB=CF=C7=CF =C5=D3=D4=D8 =CD=C1=CB=D2=CF=D3 =
=CE=C1=D0=C9=D3=C1=CE=C9=D1 =DE=C9=D3=CC=C1 =D0=D2=CF=D0=C9=D3=D8=C0?
----

то это как раз — текст, закодированный с помощью такого алгоритма. Если сделать
обратное преобразование, получится вполне осмысленное сообщение в koi8-r.

Как уже было сказано ранее, сообщение может состоять из нескольких частей,
содержащих данные различных взаимонезависимых MIME-типов (Multipart-письмо).
MIME-совместимый почтовый клиент представит такое письмо в удобоваримом виде —
вам будет показан список частей, для каждой из которых можно будет выбрать, что
с ней делать — просмотреть (если такая возможность предусмотрена) или сохранить
в файл. Пересылка вложений (присоединённых файлов, attachment) — одно из
наиболее частых применений Multipart-писем. Если вы пожелаете послать вашему
адресату, например, файл с вашей фотографией — просто вложите его в сообщение,
ваш почтовик сам закодирует его в Base64.

Для указания того, что представляет из себя содержимое письма или его части,
используются заголовки Content-Type. Например, имеющиеся в заголовках письма
строки:

[source,edit]
----
Content-Type: text/plain; charset=koi8-r
Content-Transfer-Encoding: 8bit
----

означают, что содержимое — текст в кодировке koi8-r, использовано 8-битное
кодирование, т. е. это просто текст без каких-либо преобразований; если есть

[source,edit]
----
Content-Type: image/jpeg; name="photo.jpg"
Content-Transfer-Encoding: base64
----

то — графический файл (закодированный в Base64) и т. п.

Рассмотрим некоторые наиболее популярные почтовые клиенты. Из тех, что имеют
графический интерфейс, это — http://www.mozilla.org/[Mozilla Mail] (см. статью
А. Добровольского), http://www.ximian.com/products/evolution/[Evolution],
созданный в компании Ximian, Inc, детище японского программиста Хироюки Ямамото
http://sylpheed.good-day.net/[Sylpheed] и http://kmail.kde.org/[KMail], входящий
в состав K Desktop Environment. Здесь я постараюсь осветить возможности
последних трёх почтовиков, краткая сводка которых помещёна в таблицу. Консольные
же программы, наибольшей популярностью среди которых пользуются
http://www.mutt.org/[mutt] и http://www.washington.edu/pine[pine], рассмотрены
во врезке М. Шигорина.

.Сравнительная таблица почтовых программ
[cols=",,,",]
|===
|  |Sylpheed |Evolution |KMail

|Интерфейс |GTK+ |Gnome/GTK+ |KDE/QT

|Тип ящика |MH |mbox |mbox

|Сеть: | | |

|Протоколы |POP3, APOP, IMAP4, SMTP, SMTP AUTH, NNTP |POP3, IMAP4, SMTP,
SMTP AUTH |POP3, IMAP4, SMTP, SMTP AUTH

|Несколько аккаунтов |+ |+ |+

|Автоматическая проверка почты |+ |+ |+

|Поддержка: | | |

|i18n |+ |+ |+

|Разных кодировок |+ |+ |+

|MIME |+ |+ |+

|Просмотра графических вложений |+ |+ |+

|Сортировки сообщений |+ |+ |+

|Поиска сообщений |+ |+ |+

|Постановки сообщений в очередь |+ |+ |+

|Адресной книги |+ |+ |+

|Карточек vCard в адресной книге |+ |+ |-

|Автодополнения адреса |+ |- |+

|Фильтров |+ |+ |+

|GnuPG/PGP |+ |+ |+

|Импорта/экспорта почты |+ |+ |+

|HTML |- |+ |+

|Редактирование: | | |

|Автоматическая вставка подписи |+ |+ |+

|Проверка правописания |- |+ |+

|Внешний редактор |+ |- |+

|Черновики |+ |+ |+

|Шаблоны |+ |- |-

|Автоперенос строк |+ |+ |+

|Выделение цитат |+ |+ |+

|Печать |+ |+ |+
|===

Отмечу некоторые особенности рассматриваемых программ:

* Sylpheed:
** Двойной щелчок на URL в письме вызывает указанный в настройках браузер,
который загружает этот URL.
** Можно добавлять в сообщения дополнительные заголовки, в частности, есть
поддержка X-Face — в область заголовков вставляется специальным образом
закодированная картинка; например, можно использовать фотографию.
** Есть пометка сообщений разными цветами.
** Цитирование сообщений весьма тонко настраивается.
** Можно находить и удалять дубликаты писем.
** Поддерживается получение, чтение и отправка новостей.
** От основной версии Sylpheed «отпочковалась» Sylpheed-claws, имеющая свои
особенности; в дистрибутивы она не включается.
* Evolution:
** Это не просто почтовая программа, а персональный информационный менеджер
(PIM), включающий в себя, кроме почтового клиента, календарь и планировщик
заданий. Имеется очень развитая система управления контактами.
** Есть возможность обмена данными с наладонниками, работающими под управлением
Palm-OS (в Sylpheed так же есть обмен с такими устройствами, но только данными из
адресной книги).
** Можно создавать динамически обновляемые «виртуальные папки».
** Имеется возможность скрывать прочитанные или выбранные сообщения.
* KMail:
** Можно получать уведомления о поступлении новой почты.
** Есть тесная интеграция с другими приложениями KDE, в частности, поддержка
drag'n'drop, открытие URL при щелчке на нём в Konqueror и т. д.

Если вам не требуется что-либо очень уж _особенное_, то каждая из этих программ
может удовлетворить почти любые запросы. Если ваша рабочая среда — KDE, вполне
логичным будет использование KMail; для Gnome, наверно, больше подойдут Sylpheed
или Evolution, так же как и для других оконных менеджеров — если вы не
пользуетесь KDE, то вряд ли вам захочется, чтобы KMail потянула за собой
установку KDE-шных пакетов. Консольные почтовики — самые неприхотливые и
наименее требовательны к ресурсам, при этом по своим возможностям более чем
конкурентоспособны. Вы можете попробовать поработать с каждым из этих клиентов и
тогда уже сделать свой выбор. Сделаю лишь пару замечаний из собственных
наблюдений:

* Наиболее быстро загружается из вошедших в мой обзор программ Sylpheed, она же
быстрее всего выполняет операцию получения почты из локального спула; самая
медленная в этих отношениях — Evolution, причём очень заметно.
* Поиск самый быстрый — можно сказать, мгновенный,— наоборот, у Evolution, у неё
также он наиболее развитый по своим возможностям и самый удобно устроенный.

Подчёркиваю — это мой опыт работы с этими программами; у меня очень большой
ящик, с очень большим количеством сообщений в некоторых папках, кроме того,
папок также очень много и поэтому много правил фильтрации. Если у вас таких
объёмов почты не предвидится, то и очень сильной разницы в скорости работы не
будет. Если же настроить доставку сообщений с помощью Procmail, то разница в
скорости получения почты вообще нивелируется.

Рассмотрим подробнее работу с Evolution. После её первого запуска в домашнем
каталоге создаётся каталог _evolution_ и осуществляется первоначальное
конфигурирование специальным <>. Потребуется ввести ваше имя и адрес электронной
почты, можно будет указать также название организации и выбрать файл подписи.
Последний может иметь примерно следующий вид:

[source,edit]
----
С наилучшими пожеланиями,
Василий Ферапонтович Пупкин.
mailto:vasya@pupkin.ru
----

Можете проявить фантазию, но сильно не увлекайтесь - мало кому могут понравиться
слишком длинные и экзотические варианты. На следующем экране указываем в <> <>,
если собираемся получать почту с помощью Fetchmail. Путь и имя локального яшика
можно оставить те, что будут предложены по умолчанию. Далее, в настройках <>
укажем тип сервера <> и его имя, например, <>. Дальше потребуется присвоить имя
настроенному счёту, можно его сделать счётом по умолчанию. После указания на
следующем экране часового пояса предварительная настройка завершается и вы
сможете работать с Evolution. Более подробную настройку можно сделать, выбрав в
меню Инструменты->Установки почты - добавить другие счета или отредактировать
существующие, в закладке <> - настроить цвет выделения цитат, в закладке <> -
стили написания и пересылки писем, в <> - установить кодировку символов по
умолчанию и некоторые другие. Если раньше вы пользовались другим почтовым
клиентом - можно импортировать всю полученную ранее почту в Evolution, выбрав в
меню Файл->Импортирование. Запускается <>, который поможет вам это сделать.

В левой части программы отображается панель закладок, с помощью которой можно
выбрать, что вы собираетесь делать - работать с почтой, календарём,
отредактировать ваш контакт-лист или настроить задания и т.д. Правее расположена
панель папок, в которых хранятся ваши почта, контакты, задания и календарь. Ещё
правее - утилита поиска, ниже неё во время работы с почтой вы видите список
сообщений из той папки, которая в данный момент является активной, ниже списка
расположено окно для отображения самих сообщений. Папка <> суммирует текущее
состояние вашего почтового ящика, ваши встречи, задания и другую информацию.
Можно настроить отображение списка новостей с различных порталов и получение
сводки погоды.

Если почта уже доставлена в локальный спул, можно её получить выбором в панели
инструментов <>, при этом будут также отправлены ваши сообщения из очереди, если
они там есть. Теперь можно прочитать почту, удалить ненужные сообщения (они
попадают в мусорную корзину, которую следует периодически очищать), переместить
какие-либо из них в другие папки, ответить на них, распечатать и т.д. При
создании нового письма или ответе на пришедшее к вам проверяется правописание;
можно подписать его ключом PGP и даже зашифровать, послать копии нескольким
адресатам, вложить файлы. Можно написать сообщение в формате HTML, но я делать
этого не советую - многие не любят получать такие письма, некоторые фильтруют их
как спам; по крайней мере, поинтересуйтесь об этом вначале у кашего адресата.
Написанное письмо можно отправить немедленно или поместить в очередь. Тут не
обошлось, к сожалению, без ложки дёгтя: Evolution принудительно отправляет все
сообщения закодированными в Base64 или Quoted-Printable, что, пожалуй, является
единственным серьёзным недостатком этого в остальном замечательного клиента.
Хотя среди современных почтовых программ, наверно, не найти такую, которая не
понимала бы это кодирование, но, во-первых, вашим адресатам может такое
поведение вашего почтовика не понравиться — большинство всё же предпочитает
получать письма в обычном текстовом формате, во-вторых, это увеличивает объём
письма, в-третьих, многие листы рассылки имеют опцию получения писем в
дайджестах — когда несколько писем объединяются в одно большое — в этом случае у
получающих их могут быть проблемы с прочтением ваших посланий.

Список сообщений может отображаться различными способами, например, в листах
рассылки удобно сортировать письма по дискуссиям: в меню выберите Просмотр
Список подшитых сообщений. Довольно удобной является возможность скрывать уже
прочитанные письма: Просмотр Скрыть прочитанные сообщения. Каждое письмо имеет
подробное контекстное меню - можно, например, добавить отправителя в адресную
книгу или создать правило из сообщения - фильтр или виртуальную папку.

Можно настроить фильтры, с тем чтобы хранить получаемую почту не вперемешку, а
отсортированной по тем или иным критериям. Например, удобно для каждого листа
рассылки заводить отдельную папку, письма от какого-либо постоянного адресата
хранить также в отдельном месте и т.д. Количество создаваемых папок не
ограничено, они могут содержать другие вложенные папки. Выбираем в меню
Инструменты Фильтры... Появляется список зарегистрированных правил фильтрации -
пустой, если пока их нет. Нажимаем кнопку <>, пишем название фильтра, например,
<>, указываем критерий фильтрации - <>, условие - <>, в отведённом для этого
поле пишем, что содержит - <>, выбираем действие - <> и указываем нужную папку,
которую можно сделать заранее или прямо во время настройки фильтра. Фильтры
можно редактировать, удалять и перемещать по списку - в самом верху разумнее
всего помещать те из них, которым удовлетворяет больше всего сообщений из
получаемой вами почты.

Evolution имеет отличные средства поиска - выберите папку, в которой вы хотите
найти письма, содержащие какую-либо информацию, например, выбираем папку с
листом рассылки community@altlinux.ru; определяем, где искать - <>, что искать -
<>, нажимаем кнопку <> и почти мгновенно получаем список сообщений, содержащих
то, что мы хотели найти. В каждом найденном письме слово <> будет выделено -
удобно для просмотра результатов поиска.

Одной из наиболее привлекательных особенностей Evolution является возможность
создания виртуальных папок. Допустим, мы осуществили описанный выше поиск.
Выберем теперь в утилите поиска <>, в открывшемся меню напишем название фильтра,
например, <> и заполним условия и критерии, которым должна удовлетворять эта
папка. Можно добавить источники - например, указать, что туда следует также
добавлять сообщения из папки debian, в которой хранятся письма из рассылки
debian-russian. Важно то, что физически эти письма не копируются, в отличие от
реальных папок, т.е. дополнительное место не расходуется. Теперь при поступлении
в папки community и debian новых сообщений, содержащих <>, они будут
автоматически добавляться в эту виртуальную папку. Можно также для создания
виртуальной папки выбрать в меню Инструменты Редактор виртуальных папок...

Другие возможности Evolution как персонального информационного менеджера -
календарь, задания - я рассматривать не буду, поскольку это выходит за рамки
данной статьи; всё это можно найти в довольно подробной документации.

Настроим теперь программу Fetchmail, которая будет забирать всю вашу почту со
всех почтовых ящиков, которые вы имеете (у меня их три — по одному на серверах
моих двух провайдеров, один — на eudoramail). Удобнее всего воспользоваться для
настройки специально для этого предназначенной графической конфигурилкой
Fetchmailconf. После её запуска

[source,bash]
----
[user@localhost user]$ fetchmailconf
----

вы сможете выбрать, в каком режиме она должна работать — «новичок» или
«эксперт»; если экспертом в этих вопросах вы себя не ощущаете — соглашайтесь на
первый вариант. После настройки вы получите в своём домашнем каталоге
конфигурационный файл _.fetchmailrc_. Если будете делать его «руками», не
забудьте задать для него правильные права доступа:

[source,bash]
----
[user@localhost user]$ chmod 600 .fetchmailrc
----

Вот примерно то, что вы можете получить в этом файле:

[source,edit]
----
# Configuration created Tue Oct 22 05:06:17 2002 by fetchmailconf
set logfile "/home/vasya/fetchmail.log"
set postmaster "vasya"
set bouncemail
set no spambounce
set properties ""
poll mail.mymainprovider.ru with proto POP3
       user 'rvasya' there with password 'PaSsWoRd' is 'vasya' here

skip mail.mysecondprovider.ru with proto POP3
       user 'rvasya' there with password 'pAsSwOrD' is 'vasya' here
----

Формат конфигурационного файла достаточно прозрачен — указаны имя почтового
сервера провайдера, протокол (POP3), ваши логин и пароль для почты и кому
следует отдать все полученные сообщения. Командой

[source,bash]
----
[user@localhost user]$ fetchmail
----

вы сможете забрать всю вашу почту с ящика на mail.mymainprovider.ru, ящик на
mail.mysecondprovider.ru Fetchmail проверять не будет. Для того, чтобы получить
сообщения со второго аккаунта, надо запускать Fetchmail с указанием брать почту
именно с него:

[source,bash]
----
[user@localhost user]$ fetchmail mail.mysecondprovider.ru
----

Можно теперь забрать полученную почту из спула.

Я не люблю spam. Во-первых, я — вегетарианец. Во-вторых, к сожалению (в данном
случае, скорее, к счастью) не умею читать ни по-китайски, ни по-корейски, а
именно на этих языках больше всего сыплется в мой ящик всевозможного рекламного
хлама. В-третьих, вообще не люблю рекламу, особенно когда мне её пытаются
втюхать принудительным порядком. Если вы заведёте себе адрес электронной почты,
то рано или поздно (разве что не будете его вообще использовать) также начнёте
получать всевозможную дрянь, начиная с предложений зарабатывать $1 000 000 в
неделю и кончая посланиями зазывал со свежеиспечённых порно-ресурсов. Особенно
много мусора приходится выгребать из бесплатных Интернет-ящиков. Постарайтесь
поменьше «засвечивать» свой ящик в Сети, особенно тот, что вы откроете у своего
провайдера. Но что же делать, если меры предосторожности не помогли, и вы стали
получать на свой адрес спам? Для этого нужно использовать фильтрацию почты.

Настройку фильтров в почтовом клиенте мы уже рассматривали, при этом непрошенных
гостей вашего почтового ящика можно попросить занять подобающее им место в
мусорной корзине. Но более интересным будет такой вариант фильтрации, при
котором эти гости не пройдут дальше порога — применим для этого возможности
Procmail.

Эта весьма полезная программа использует для своей работы конфигурационный файл
_.procmailrc_, который должен находиться в вашем домашнем каталоге. Создадим
его:

[source,bash]
----
[user@localhost user]$ touch .procmailrc
[user@localhost user]$ chmod 600 .procmailrc
----

В этом файле определяются правила, которые указывают Procmail, какие действия
надо предпринять после получения сообщения — сохранить его, игнорировать,
автоматически на него ответить, обработать тем или иным образом и т. д. Формат
его следующий:

* Любая строка, начинающаяся с символа [.kbd]###, считается комментарием,
Procmail её игнорирует.
* Строки, начинающиеся с ``:0`` или ``:0:``, указывают на начало нового
правила, которое говорит Procmail, что следует делать с сообщением.
* Строки, начинающиеся с ``*``, обозначают условие выполнения правила;
используются для определения сообщения, которое необходимо обработать этим
правилом.
* Оставшиеся строки рассматриваются как команды — например, удалить, переслать,
сохранить сообщение и т. д.
* В этом файле могут определяться некоторые переменные окружения.

Некоторые переменные, используемые Procmail, имеют предопределённые значения,
большинство из них можно обычно не менять, при этом вы можете ввести и
использовать свои.

[source,edit]
----
# Определим, куда должны доставляться сообщения,
# к которым не будут применены фильтры.
EVO=$HOME/evolution/local/Inbox
# Ещё ряд полезных переменных для простоты записи правил.
INBOX=$EVO
SUBEVO=$EVO/subfolders
COMMUNITY=$SUBEVO/community/mbox
DEBIAN=$SUBEVO/debian/mbox
SPAM=$SUBEVO/spam/mbox
# Имя файла, в котором будут зарегистрированы
# действия Procmail.
LOGFILE =$HOME/procmail.log
# Полезно в процессе отладки для расширенной диагностики.
VERBOSE=yes
# Создание резюме в $LOGFILE для каждого применённого правила.
LOGABSTRACT=all

# Определим правила фильтрации. Отрабатываются последовательно.

# Два списка рассылки. Точки в адресах экранируются,
# чтобы они не воспринимались как метасимволы.

# В заголовке "Кому" имеется адрес community@altlinux.ru
:0:
* ^To:.*community@altlinux\.ru
$COMMUNITY
# В заголовке "Кому" или "Копия" имеется адрес
# debian-russian@lists.debian.org
:0:
* ^(To|Cc:).*debian-russian@lists\.debian\.org
$DEBIAN

# С этого домена мне шлют только спам, выбросить сразу.
:0
* ^From:.*@163\.com
/dev/null

# Тема письма содержит сочетание "porno". Скорее всего, спам.
:0:
* ^Subject:.*porno
$SPAM

# Всё оставшееся -- сюда.
:0:
$INBOX/mbox
----

Общий синтаксис правила в _.procmailrc_ следующий:

[source,edit]
----
:0 [опции] [ : [исполняемый файл] ]
* условие
* условие
...
* условие
команда
----

Отличие правила, начинающегося с ``:0:`` от ``:0``, заключается в том,
что в первом случае осуществляется блокировка файла, в который происходит
доставка сообщения — это нужно для обеспечения того, чтобы одновременно
какой-либо другой процесс не стал что-то писать в этот же файл. Опции
определяют, к чему применяется условие или что передаётся команде и т. д.
Например, опция ``H`` означает, что условие применяется к заголовку
сообщения (действует по умолчанию), опция ``D`` — что следует различать
верхний и нижний регистры, опция ``b`` — команде передаётся тело письма
и т. д. Можно объединить несколько опций, записав их подряд. После этого идут
условия, по одному в строке, каждое из них должно начинаться символом ``*``,
завершается правило командой — что делать, если выполнены условия. Для записи
условий применяются так называемые регулярные выражения, являющиеся очень мощным
и эффективным средством обработки текстов. В регулярных выражениях используются
специальные символы — метасимволы, среди которых, например, имеются следующие:

* ``^`` Начало строки.
* ``$`` Конец строки.
* ``.`` Любой символ, за исключением конца строки.
* ``*`` Ноль или более раз. Пример: ``.*`` — любая последовательность
символов, кроме конца строки.
* ``+`` Один или более раз. Пример: ``a+`` — последовательность из
одного или более символов ``a``.
* ``?`` Ноль или один раз. Пример: ``a?`` — ноль или один символ
``a``.
* ``[]`` Любой символ из числа заключённых в скобки; можно задать диапазон.
Пример: ``[a-c]`` — любой символ среди ``a``, ``b``, ``c``.
* ``[^]`` Любой символ, кроме указанных в скобках. Пример: ``[^ab]`` —
любой символ, кроме ``a``, ``b`` и конца строки.
* ``|`` Или. Пример: ``a|b`` — или ``a`` или ``b``.

Если ваша почта хранится в формате MH, то при написании пункта назначения
сообщений следует имя каталога завершать символами ``/.``:

[source,edit]
----
/home/vasya/mail/inbox/.
----

Приведённый пример конфигурационного файла — намеренно очень упрощенный; как его
писать и множество примеров правил можно найти в документации к Procmail.

Для применения модифицируем рассмотренный выше файл _.fetchmailrc_:

[source,edit]
----
...
poll mail.mymainprovider.ru with proto POP3
       user 'rvasya' there with password 'PaSsWoRd' is 'vasya' here
       mda "/usr/bin/procmail -d %T"
...
----

Сейчас вся почта, забираемая Fetchmail с сервера, будет сразу роздана Procmail
по пунктам назначения.

Давайте попробуем возвести бастион эпистолам этих охальников ещё дальше — не
пустим их вообще на ваш компьютер, удалив прямо на почтовом сервере.
Воспользуемся для этого программой
http://mailfilter.sourceforge.net/[mailfilter]. Создаём в домашнем каталоге её
конфигурационный файл:

[source,bash]
----
[user@localhost user]$ touch .mailfilterrc
[user@localhost user]$ chmod 600 .mailfilterrc
----

Теперь его надо заполнить содержимым. Также, как в конфигурационном файле
Procmail, здесь используются регулярные выражения, можно вносить комментарии:

[source,edit]
----
# Имя почтового сервера.
SERVER=www.eudoramail.com
# Имя пользователя на сервере.
USER=ruser
# Пароль.
PASS=PaSsWoRd
# Используемый протокол. Оставить pop3, пока поддерживается только он.
PROTOCOL=pop3
# Порт POP3-сервера.
PORT=110
# Порядок предыдущих строк не следует менять, как и регистр ключевых слов.
# Можно задать несколько аккаунтов.
# Имя файла журнала. Файл должен существовать и иметь права на запись,
# так же как и каталог, в котором он расположен.
LOGFILE=/home/user/mailfilter.log
# Не следует различать регистр букв.
REG_CASE=no
# Временно включим режим тестирования. mailfilter только симулирует
# удаление спама. После проверки правильности работы уберём эту строку.
TEST=yes
# Удаляем иногда возникающие дубликаты писем.
DEL_DUPLICATES=yes

# Пишем фильтры.
# Удалить всю почту, поступившую с домена 163.com.
DENY=^From:.*@163\.com
# Если есть адресат с этого домена, от которого надо получать
# почту, специально это разрешим:
ALLOW=^From:.*gooduser@163\.com
# Удалить всю почту от baduser@hotmail.com.
DENY=^From:.*baduser@hotmail\.com
# Удалить все сообщения с темами, в которых встречается "porno".
DENY=^Subject:.*porno
----

Можно теперь запустить mailfilter из командной строки, он соединится с
POP3-сервером и удалит почту в соответствии с заданными правилами. Результаты
его работы можно посмотреть в лог-файле. Если модифицировать _.fetchmailrc_:

[source,edit]
----
...
poll mail.mymainprovider.ru with proto POP3
       user 'rvasya' there with password 'PaSsWoRd' is 'vasya' here
       mda "/usr/bin/procmail -d %T"
       preconnect "/usr/bin/mailfilter"
...
----

то сначала отработает Mailfilter, а затем не удалённая почта будет получена и
доставлена по назначению [#back_2]## ##link:#foot_2[[2]].

При написании конфигурационных файлов Procmail и, особенно, Mailfilter, следует
быть очень внимательным, чтобы не пришлось искать свою почту по всей файловой
системе или — ещё хуже — кричать «Мама, роди меня обратно!», обнаружив в логах,
что самое важное в вашей жизни письмо было гильотинировано на сервере или
отправлено Procmail в _/dev/null_ уже во время доставки. Лучше перестраховаться
и разгрести папку «spam» в почтовике, чем оказаться в ситуации безвозвратной
потери необходимого вам сообщения. Например, при рассмотренной выше
конфигурации, будут уничтожаться сообщения с темами не только «My new pornosite»
и подобными им, но и «Problemy oporno-dvigatelnogo apparata», «Spornoe mnenie»
и т. д. Советую отсекать на сервере только явно заведомый спам, а
«подозрительные» письма направлять в отведённую для этого папку — обычно там
бывает немного сообщений, и, как правило, достаточно просмотреть заголовки,
чтобы решить их судьбу.

'''''

{empty}[#foot_1]#[1]# Это не относится к другим государствам из бывшего СССР, в
которых используется кириллическая письменность — стандартным там может быть
другой набор символов. link:#back_1[[вернуться]]

{empty}[#foot_1]#[2]# Если Mailfilter не сможет работать по какой-либо причине,
почта получена не будет. link:#back_2[[вернуться]]
